name: octor
description: >-
  Server-side framework built upon dart:io:HttpServer.
  It's self contained Http framework which keeps codebase simple
  by having minimal possible dependencies.
version: 0.0.3
homepage: https://github.com/OctoDart/octor
repository: https://github.com/OctoDart/octor
issue_tracker: https://github.com/OctoDart/octor/issues
environment:
  sdk: '>=2.12.2 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
