name: octor
description: Server-side framework built upon dart:io:HttpServer. It's self contained Http framework which keeps simple by having minimal possible dependencies.
version: 0.0.3
homepage: https://github.com/OctoDart/octor

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
